// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/backend.proto

package backend

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DHT messages
type ID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type EmptyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReq) Reset()         { *m = EmptyReq{} }
func (m *EmptyReq) String() string { return proto.CompactTextString(m) }
func (*EmptyReq) ProtoMessage()    {}
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{2}
}

func (m *EmptyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReq.Unmarshal(m, b)
}
func (m *EmptyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReq.Marshal(b, m, deterministic)
}
func (m *EmptyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReq.Merge(m, src)
}
func (m *EmptyReq) XXX_Size() int {
	return xxx_messageInfo_EmptyReq.Size(m)
}
func (m *EmptyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReq.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReq proto.InternalMessageInfo

type EmptyRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRes) Reset()         { *m = EmptyRes{} }
func (m *EmptyRes) String() string { return proto.CompactTextString(m) }
func (*EmptyRes) ProtoMessage()    {}
func (*EmptyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{3}
}

func (m *EmptyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRes.Unmarshal(m, b)
}
func (m *EmptyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRes.Marshal(b, m, deterministic)
}
func (m *EmptyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRes.Merge(m, src)
}
func (m *EmptyRes) XXX_Size() int {
	return xxx_messageInfo_EmptyRes.Size(m)
}
func (m *EmptyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRes.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRes proto.InternalMessageInfo

// storage messages
type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{6}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{7}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CanStoreRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanStoreRequest) Reset()         { *m = CanStoreRequest{} }
func (m *CanStoreRequest) String() string { return proto.CompactTextString(m) }
func (*CanStoreRequest) ProtoMessage()    {}
func (*CanStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{10}
}

func (m *CanStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanStoreRequest.Unmarshal(m, b)
}
func (m *CanStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanStoreRequest.Marshal(b, m, deterministic)
}
func (m *CanStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanStoreRequest.Merge(m, src)
}
func (m *CanStoreRequest) XXX_Size() int {
	return xxx_messageInfo_CanStoreRequest.Size(m)
}
func (m *CanStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CanStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CanStoreRequest proto.InternalMessageInfo

func (m *CanStoreRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CanStoreResponse struct {
	Answer               bool     `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CanStoreResponse) Reset()         { *m = CanStoreResponse{} }
func (m *CanStoreResponse) String() string { return proto.CompactTextString(m) }
func (*CanStoreResponse) ProtoMessage()    {}
func (*CanStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{11}
}

func (m *CanStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CanStoreResponse.Unmarshal(m, b)
}
func (m *CanStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CanStoreResponse.Marshal(b, m, deterministic)
}
func (m *CanStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CanStoreResponse.Merge(m, src)
}
func (m *CanStoreResponse) XXX_Size() int {
	return xxx_messageInfo_CanStoreResponse.Size(m)
}
func (m *CanStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CanStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CanStoreResponse proto.InternalMessageInfo

func (m *CanStoreResponse) GetAnswer() bool {
	if m != nil {
		return m.Answer
	}
	return false
}

type RangeGetRequest struct {
	Start                string   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeGetRequest) Reset()         { *m = RangeGetRequest{} }
func (m *RangeGetRequest) String() string { return proto.CompactTextString(m) }
func (*RangeGetRequest) ProtoMessage()    {}
func (*RangeGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{12}
}

func (m *RangeGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeGetRequest.Unmarshal(m, b)
}
func (m *RangeGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeGetRequest.Marshal(b, m, deterministic)
}
func (m *RangeGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeGetRequest.Merge(m, src)
}
func (m *RangeGetRequest) XXX_Size() int {
	return xxx_messageInfo_RangeGetRequest.Size(m)
}
func (m *RangeGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RangeGetRequest proto.InternalMessageInfo

func (m *RangeGetRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *RangeGetRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{13}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IsLeavingRes struct {
	Leaving              bool     `protobuf:"varint,1,opt,name=leaving,proto3" json:"leaving,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeavingRes) Reset()         { *m = IsLeavingRes{} }
func (m *IsLeavingRes) String() string { return proto.CompactTextString(m) }
func (*IsLeavingRes) ProtoMessage()    {}
func (*IsLeavingRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{14}
}

func (m *IsLeavingRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeavingRes.Unmarshal(m, b)
}
func (m *IsLeavingRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeavingRes.Marshal(b, m, deterministic)
}
func (m *IsLeavingRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeavingRes.Merge(m, src)
}
func (m *IsLeavingRes) XXX_Size() int {
	return xxx_messageInfo_IsLeavingRes.Size(m)
}
func (m *IsLeavingRes) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeavingRes.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeavingRes proto.InternalMessageInfo

func (m *IsLeavingRes) GetLeaving() bool {
	if m != nil {
		return m.Leaving
	}
	return false
}

type State struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_b81549028379a959, []int{15}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*ID)(nil), "backend.ID")
	proto.RegisterType((*Node)(nil), "backend.Node")
	proto.RegisterType((*EmptyReq)(nil), "backend.EmptyReq")
	proto.RegisterType((*EmptyRes)(nil), "backend.EmptyRes")
	proto.RegisterType((*GetRequest)(nil), "backend.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "backend.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "backend.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "backend.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "backend.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "backend.DeleteResponse")
	proto.RegisterType((*CanStoreRequest)(nil), "backend.CanStoreRequest")
	proto.RegisterType((*CanStoreResponse)(nil), "backend.CanStoreResponse")
	proto.RegisterType((*RangeGetRequest)(nil), "backend.RangeGetRequest")
	proto.RegisterType((*KV)(nil), "backend.KV")
	proto.RegisterType((*IsLeavingRes)(nil), "backend.IsLeavingRes")
	proto.RegisterType((*State)(nil), "backend.State")
}

func init() { proto.RegisterFile("backend/backend.proto", fileDescriptor_b81549028379a959) }

var fileDescriptor_b81549028379a959 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x6f, 0x12, 0x41,
	0x14, 0x86, 0xb5, 0x5b, 0xe8, 0xe1, 0xd2, 0x3a, 0x52, 0xc4, 0x4d, 0x34, 0x75, 0x7c, 0x21, 0x4d,
	0xa5, 0xa6, 0x36, 0x12, 0x7d, 0x93, 0x62, 0x09, 0xc1, 0x34, 0x64, 0x49, 0x78, 0x9f, 0x32, 0x47,
	0xb2, 0x01, 0x67, 0xe9, 0xce, 0x2c, 0x06, 0x7f, 0x88, 0xbf, 0xd7, 0xec, 0x30, 0x7b, 0xe1, 0x52,
	0x2f, 0x4f, 0x9c, 0xcb, 0x77, 0x2e, 0xfb, 0xf1, 0x9d, 0x81, 0xd3, 0x7b, 0x36, 0x99, 0xa1, 0xe0,
	0x97, 0xe6, 0xb7, 0xb5, 0x08, 0x7c, 0xe5, 0x93, 0x82, 0x71, 0x69, 0x0d, 0xac, 0x7e, 0x97, 0x54,
	0xc1, 0xf2, 0x78, 0x23, 0x7f, 0x96, 0x6f, 0x1e, 0xb9, 0x96, 0xc7, 0xe9, 0x39, 0x1c, 0xdc, 0xf9,
	0x1c, 0xb7, 0xe3, 0x84, 0xc0, 0x01, 0xe3, 0x3c, 0x68, 0x58, 0x3a, 0xa2, 0x6d, 0x0a, 0x50, 0xfc,
	0xf2, 0x7d, 0xa1, 0x56, 0x2e, 0x3e, 0x64, 0x6c, 0x49, 0x5f, 0x01, 0xf4, 0x50, 0xb9, 0xf8, 0x10,
	0xa2, 0x54, 0xe4, 0x04, 0x9e, 0xcc, 0x70, 0x65, 0x5a, 0x45, 0x26, 0x6d, 0x43, 0x49, 0xe7, 0xe5,
	0xc2, 0x17, 0x12, 0x49, 0x0d, 0xec, 0x25, 0x9b, 0x87, 0x68, 0x20, 0x6b, 0x27, 0x1a, 0x28, 0xbd,
	0x9f, 0xa8, 0x07, 0xda, 0xae, 0xb6, 0xe9, 0x35, 0xc0, 0x30, 0x7c, 0xbc, 0x71, 0xda, 0xc9, 0xca,
	0x74, 0xa2, 0x15, 0x28, 0xe9, 0xaa, 0xf5, 0x38, 0xfa, 0x1a, 0x2a, 0x5d, 0x9c, 0xa3, 0xc2, 0xc7,
	0x17, 0x6c, 0x42, 0x35, 0x86, 0x98, 0x1d, 0xeb, 0x70, 0x28, 0x15, 0x53, 0xa1, 0xd4, 0x30, 0xdb,
	0x35, 0x1e, 0x7d, 0x03, 0xc7, 0x37, 0x4c, 0x8c, 0x94, 0x1f, 0xfc, 0xa1, 0xdd, 0x39, 0x9c, 0xa4,
	0xa0, 0xb4, 0x21, 0x13, 0xf2, 0x07, 0x06, 0x1a, 0x58, 0x74, 0x8d, 0x47, 0x3f, 0xc2, 0xb1, 0xcb,
	0xc4, 0x14, 0x33, 0x04, 0xd6, 0xc0, 0x96, 0x8a, 0x05, 0x2a, 0xe6, 0x47, 0x3b, 0xd1, 0x18, 0x14,
	0xdc, 0x7c, 0x69, 0x64, 0xd2, 0x0b, 0xb0, 0x06, 0xe3, 0x7f, 0x66, 0xa5, 0x09, 0xe5, 0xbe, 0xfc,
	0x8a, 0x6c, 0xe9, 0x89, 0xa9, 0x8b, 0x92, 0x34, 0xa0, 0x30, 0x5f, 0x7b, 0x66, 0xa3, 0xd8, 0xa5,
	0x2f, 0xc1, 0x1e, 0x29, 0xa6, 0xd0, 0x2c, 0xa2, 0xd0, 0x70, 0xb0, 0x76, 0xae, 0x7e, 0xd9, 0x50,
	0xe8, 0xac, 0x35, 0x45, 0xae, 0xa0, 0xdc, 0x43, 0x35, 0x0a, 0x27, 0x13, 0x94, 0xd2, 0x0f, 0xc8,
	0xd3, 0x56, 0x2c, 0xbe, 0x58, 0x28, 0x4e, 0x25, 0x09, 0x45, 0x3a, 0xa3, 0x39, 0x72, 0x0d, 0xd5,
	0x1e, 0xaa, 0x61, 0x80, 0x1c, 0xff, 0xa3, 0xea, 0x2d, 0x54, 0x6e, 0x3d, 0xc1, 0xd3, 0x51, 0xa5,
	0x04, 0xd1, 0xef, 0xee, 0xc2, 0x3f, 0x40, 0xfd, 0x66, 0xee, 0x4b, 0x94, 0xd1, 0xa0, 0x09, 0x72,
	0x4f, 0x4c, 0x6f, 0x3d, 0x31, 0xc5, 0xbf, 0xd5, 0x5d, 0xc0, 0xe1, 0x9d, 0xaf, 0xbc, 0x6f, 0x2b,
	0xb2, 0x99, 0x72, 0x76, 0x76, 0x94, 0x34, 0x47, 0xda, 0x70, 0x94, 0x70, 0xba, 0xef, 0x2b, 0x4e,
	0xd3, 0x59, 0x19, 0xea, 0x69, 0x8e, 0x5c, 0x42, 0x31, 0xe2, 0x4d, 0xb3, 0xbc, 0xa7, 0xae, 0x9a,
	0x84, 0x34, 0x44, 0x93, 0x66, 0xf7, 0x50, 0x0d, 0xc6, 0xe4, 0x59, 0x92, 0x4a, 0x15, 0xe3, 0xd4,
	0x36, 0x83, 0x46, 0xf8, 0xba, 0x6a, 0x18, 0x6e, 0x56, 0xa5, 0xf7, 0x94, 0xa9, 0xca, 0x9e, 0x4b,
	0x8e, 0x7c, 0x02, 0xbb, 0x8b, 0xf3, 0xc1, 0x98, 0xd4, 0x13, 0xc0, 0xc6, 0x01, 0x39, 0xcf, 0x77,
	0xe2, 0x49, 0xed, 0x67, 0x28, 0xc6, 0xd2, 0x27, 0x8d, 0x04, 0xb6, 0x75, 0x32, 0xce, 0x8b, 0x3d,
	0x99, 0xa4, 0x45, 0x1b, 0x20, 0xbe, 0x88, 0xc1, 0x38, 0xd3, 0x64, 0xeb, 0x4c, 0x9c, 0xf4, 0x8f,
	0x1c, 0x8c, 0x69, 0xee, 0x5d, 0xbe, 0x73, 0x06, 0x55, 0xe4, 0x53, 0x9c, 0x2d, 0x5b, 0x46, 0x9e,
	0x9d, 0xb2, 0x31, 0x86, 0xd1, 0x4b, 0x38, 0xcc, 0xdf, 0x1f, 0xea, 0x27, 0xf1, 0xfd, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd2, 0x82, 0x3e, 0x39, 0x2b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	// DHT RPCs
	// Gets successor of this node
	GetSuccessor(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Node, error)
	// Gets predecessor of this node
	GetPredecessor(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Node, error)
	// find successor node to ID, may initiate other RPC calls
	FindSuccessor(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error)
	// find the closest preeceding finger to id
	ClosestPrecedingFinger(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error)
	// notify node of possible predecessor change
	Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyRes, error)
	// check if node is leaving the dht ring
	IsLeaving(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*IsLeavingRes, error)
	// get the node state: Created, Joined, or Ready
	GetState(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*State, error)
	// storage RPCs
	// get value associated with key from remote edgekv group
	GetKV(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// create or update value associated with key from remote edgekv group
	PutKV(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// delete key-value pair from remote edgekv group
	DelKV(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// check if the node is responsible for a key or not
	CanStore(ctx context.Context, in *CanStoreRequest, opts ...grpc.CallOption) (*CanStoreResponse, error)
	// get KV pairs in a specific range
	RangeGetKV(ctx context.Context, in *RangeGetRequest, opts ...grpc.CallOption) (Backend_RangeGetKVClient, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) GetSuccessor(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/backend.Backend/GetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetPredecessor(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/backend.Backend/GetPredecessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) FindSuccessor(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/backend.Backend/FindSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ClosestPrecedingFinger(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/backend.Backend/ClosestPrecedingFinger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyRes, error) {
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, "/backend.Backend/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) IsLeaving(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*IsLeavingRes, error) {
	out := new(IsLeavingRes)
	err := c.cc.Invoke(ctx, "/backend.Backend/IsLeaving", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetState(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := c.cc.Invoke(ctx, "/backend.Backend/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetKV(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/GetKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) PutKV(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/PutKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) DelKV(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/DelKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CanStore(ctx context.Context, in *CanStoreRequest, opts ...grpc.CallOption) (*CanStoreResponse, error) {
	out := new(CanStoreResponse)
	err := c.cc.Invoke(ctx, "/backend.Backend/CanStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) RangeGetKV(ctx context.Context, in *RangeGetRequest, opts ...grpc.CallOption) (Backend_RangeGetKVClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Backend_serviceDesc.Streams[0], "/backend.Backend/RangeGetKV", opts...)
	if err != nil {
		return nil, err
	}
	x := &backendRangeGetKVClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Backend_RangeGetKVClient interface {
	Recv() (*KV, error)
	grpc.ClientStream
}

type backendRangeGetKVClient struct {
	grpc.ClientStream
}

func (x *backendRangeGetKVClient) Recv() (*KV, error) {
	m := new(KV)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	// DHT RPCs
	// Gets successor of this node
	GetSuccessor(context.Context, *EmptyReq) (*Node, error)
	// Gets predecessor of this node
	GetPredecessor(context.Context, *EmptyReq) (*Node, error)
	// find successor node to ID, may initiate other RPC calls
	FindSuccessor(context.Context, *ID) (*Node, error)
	// find the closest preeceding finger to id
	ClosestPrecedingFinger(context.Context, *ID) (*Node, error)
	// notify node of possible predecessor change
	Notify(context.Context, *Node) (*EmptyRes, error)
	// check if node is leaving the dht ring
	IsLeaving(context.Context, *EmptyReq) (*IsLeavingRes, error)
	// get the node state: Created, Joined, or Ready
	GetState(context.Context, *EmptyReq) (*State, error)
	// storage RPCs
	// get value associated with key from remote edgekv group
	GetKV(context.Context, *GetRequest) (*GetResponse, error)
	// create or update value associated with key from remote edgekv group
	PutKV(context.Context, *PutRequest) (*PutResponse, error)
	// delete key-value pair from remote edgekv group
	DelKV(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// check if the node is responsible for a key or not
	CanStore(context.Context, *CanStoreRequest) (*CanStoreResponse, error)
	// get KV pairs in a specific range
	RangeGetKV(*RangeGetRequest, Backend_RangeGetKVServer) error
}

// UnimplementedBackendServer can be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (*UnimplementedBackendServer) GetSuccessor(ctx context.Context, req *EmptyReq) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessor not implemented")
}
func (*UnimplementedBackendServer) GetPredecessor(ctx context.Context, req *EmptyReq) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredecessor not implemented")
}
func (*UnimplementedBackendServer) FindSuccessor(ctx context.Context, req *ID) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (*UnimplementedBackendServer) ClosestPrecedingFinger(ctx context.Context, req *ID) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosestPrecedingFinger not implemented")
}
func (*UnimplementedBackendServer) Notify(ctx context.Context, req *Node) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (*UnimplementedBackendServer) IsLeaving(ctx context.Context, req *EmptyReq) (*IsLeavingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLeaving not implemented")
}
func (*UnimplementedBackendServer) GetState(ctx context.Context, req *EmptyReq) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (*UnimplementedBackendServer) GetKV(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKV not implemented")
}
func (*UnimplementedBackendServer) PutKV(ctx context.Context, req *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutKV not implemented")
}
func (*UnimplementedBackendServer) DelKV(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelKV not implemented")
}
func (*UnimplementedBackendServer) CanStore(ctx context.Context, req *CanStoreRequest) (*CanStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanStore not implemented")
}
func (*UnimplementedBackendServer) RangeGetKV(req *RangeGetRequest, srv Backend_RangeGetKVServer) error {
	return status.Errorf(codes.Unimplemented, "method RangeGetKV not implemented")
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_GetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/GetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetSuccessor(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/GetPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetPredecessor(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/FindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).FindSuccessor(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ClosestPrecedingFinger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ClosestPrecedingFinger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/ClosestPrecedingFinger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ClosestPrecedingFinger(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Notify(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_IsLeaving_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).IsLeaving(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/IsLeaving",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).IsLeaving(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetState(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/GetKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetKV(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_PutKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).PutKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/PutKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).PutKV(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_DelKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).DelKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/DelKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).DelKV(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CanStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CanStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.Backend/CanStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CanStore(ctx, req.(*CanStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_RangeGetKV_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeGetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendServer).RangeGetKV(m, &backendRangeGetKVServer{stream})
}

type Backend_RangeGetKVServer interface {
	Send(*KV) error
	grpc.ServerStream
}

type backendRangeGetKVServer struct {
	grpc.ServerStream
}

func (x *backendRangeGetKVServer) Send(m *KV) error {
	return x.ServerStream.SendMsg(m)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuccessor",
			Handler:    _Backend_GetSuccessor_Handler,
		},
		{
			MethodName: "GetPredecessor",
			Handler:    _Backend_GetPredecessor_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Backend_FindSuccessor_Handler,
		},
		{
			MethodName: "ClosestPrecedingFinger",
			Handler:    _Backend_ClosestPrecedingFinger_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Backend_Notify_Handler,
		},
		{
			MethodName: "IsLeaving",
			Handler:    _Backend_IsLeaving_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Backend_GetState_Handler,
		},
		{
			MethodName: "GetKV",
			Handler:    _Backend_GetKV_Handler,
		},
		{
			MethodName: "PutKV",
			Handler:    _Backend_PutKV_Handler,
		},
		{
			MethodName: "DelKV",
			Handler:    _Backend_DelKV_Handler,
		},
		{
			MethodName: "CanStore",
			Handler:    _Backend_CanStore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RangeGetKV",
			Handler:       _Backend_RangeGetKV_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend/backend.proto",
}
