NUM_SERVERS = 3
NUM_CLIENTS = 1
NUM_VNODES = NUM_SERVERS + NUM_CLIENTS

SERVER_VNODES = []
CLIENT_VNODES = []

for i in 1..NUM_SERVERS
  SERVER_VNODES.push("etcd-#{i}")
end

for i in 1..NUM_CLIENTS
  CLIENT_VNODES.push("cli-#{i}")
end

VNODE_LIST = SERVER_VNODES + CLIENT_VNODES