NUM_GROUPS = 3
NUM_SRVR_PER_GROUP = 3
NUM_GATEWAYS = NUM_GROUPS
NUM_SERVERS = NUM_GROUPS * NUM_SRVR_PER_GROUP
NUM_CLIENTS = NUM_GROUPS # one client for each edge group
NUM_VNODES = NUM_SERVERS + NUM_GATEWAYS + NUM_CLIENTS

SERVER_VNODES = []
GATEWAY_VNODES = []
CLIENT_VNODES = []

for i in 1..NUM_SERVERS
  SERVER_VNODES.push("edge-#{i}")
end

for i in 1..NUM_GATEWAYS
  GATEWAY_VNODES.push("gw-#{i}")
end

for i in 1..NUM_CLIENTS
  CLIENT_VNODES.push("cli-#{i}")
end

VNODE_LIST = SERVER_VNODES + GATEWAY_VNODES + CLIENT_VNODES

SETUP = "cloud"

ETCD_LOCAL_CLIENT_PORT = 2379
ETCD_GLOBAL_CLIENT_PORT = 2381
ETCD_LOCAL_PEER_PORT = 2380
ETCD_GLOBAL_PEER_PORT = 2382

EDGE_PORT = 2385

GATEWAY_PORT = 5554

EDGEKV_PARENT_DIR = '/root/go/src/github.com/ksonbol' 
SSH_KEY_PATH = '/home/ksonbol/.ssh/id_rsa'
EDGE_FILE = 'bin/edge'
GATEWAY_FILE = "bin/gateway"
CLI_FILE = 'bin/client'
